language: go

go:
  - 1.6.2

services:
  - mongodb

env:
  global:
    - GO15VENDOREXPERIMENT=0
    - TIDEPOOL_CONFIG_DIRECTORY="${PWD}/_config"

script:
  - make ci-deploy

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(git ls-files -o deploy/platform/platform-*.tar.gz | tr "\n" ":")
    target_paths:
    - /

notifications:
  email:
    on_success: change
    on_failure: always
