sudo: false

language: go

go:
  - 1.6.3

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
    - /
  code_climate:
    repo_token: 91ded9b66924acbe830541ab3593daf535f05f7c6db91b5cbd2d26dcf37da0b8

services:
  - mongodb

env:
  global:
    - TIDEPOOL_CONFIG_DIRECTORY="${PWD}/_config"

script:
  - make ci-deploy

notifications:
  email:
    on_success: change
    on_failure: always
