language: go

go:
  - 1.6

services:
  - mongodb

env:
  global:
    - GO15VENDOREXPERIMENT=0
    - TIDEPOOL_CONFIG_DIRECTORY="${PWD}/_config"

script:
  - make pre-build
  - make build
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
